# Generated by Django 2.2.5 on 2019-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.TextField()),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('children', models.ManyToManyField(to='my_cv_app.ValueItem')),
            ],
        ),
    ]
